package com.digital.opuserp.util;

public class ChecarCidadeUtil {

	public static boolean validar(String cidade1){
		String[] cidades_validas = new String[]{"ABREU E LIMA","AFOGADOS DA INGAZEIRA","AFRANIO","AGRESTINA","AGUA PRETA","AGUAS BELAS","ALAGOINHA","ALIANCA","ALTINHO","AMARAJI","ANGELIM","ARACOIABA","ARARIPINA","ARCOVERDE","BARRA DE GUABIRABA", "BARREIROS","BELEM DE MARIA","BELEM DE SAO FRANCISCO","BELO JARDIM","BETANIA","BEZERROS","BODOCO", "BOM CONSELHO","BOM JARDIM","BONITO","BREJAO","BREJINHO","BREJO DA MADRE DE DEUS","BUENOS AIRES", "BUIQUE","CABO DE SANTO AGOSTINHO","CABROBO","CACHOEIRINHA","CAETES","CALCADO","CALUMBI","CAMARAGIBE","CAMOCIM DE SAO FELIX","CAMUTANGA","CANHOTINHO","CAPOEIRAS","CARNAUBA","CARNAUBEIRA DA PENHA","CARPINA","CARUARU","CASINHAS","CATENDE","CEDRO","CHA DE ALEGRIA","CHA GRANDE","CONDADO","CORRENTES","CORTES","CUMARU","CUPIRA","CUSTODIA","DORMENTES","ESCADA","EXU","FEIRA NOVA","FERNANDO DE NORONHA","FERREIROS","FLORES","FLORESTA","FREI MIGUELINHO","GAMELEIRA","GARANHUNS","GLORIA DO GOITA","GOIANA","GRANITO", "GRAVATA","IATI","IBIMIRIM","IBIRAJUBA","IGARASSU","IGUARACI","INAJA","INGAZEIRA","IPOJUCA","IPUBI", "ITACURUBA","ITAIBA","ILHA DE ITAMARACA","ITAMBE","ITAPETIM","ITAPISSUMA","ITAQUITINGA", "JABOATAO DOS GUARARAPES","JAQUEIRA","JATAOBA","JATOBA","JOAO ALFREDO","JOAQUIM NABUCO", "JUCATI","JUPI","JUREMA","LAGOA DO CARRO","LAGOA DO ITAENGA","LAGOA DO OURO","LAGOA DOS GATOS", "LAGOA GRANDE","LAJEDO","LIMOEIRO","MACAPARANA","MACHADOS","MANARI","MARAIAL","MIRANDIBA","MORENO","NAZARE DA MATA","OLINDA","OROBO","OROCO","OURICURI","PALMARES","PALMEIRINA","PANELAS","PARANATAMA", "PARNAMIRIM","PASSIRA","PAUDALHO","PAULISTA","PEDRA","PESQUEIRA","PETROLANDIA","PETROLINA","POCAO", "POMBOS","PRIMAVERA","QUIPAPA","QUIXABA","RECIFE","RIACHO DAS ALMAS","RIBEIRAO","RIO FORMOSO", "SAIRE","SALGADINHO","SALGUEIRO","SALOE","SANHARO","SANTA CRUZ","SANTA CRUZ DA BAIXA VERDE","SANTA CRUZ DO CAPIBARIBE","SANTA FILOMENA","SANTA MARIA DA BOA VISTA","SANTA MARIA DO CAMBUCA",	"SANTA TEREZINHA","SAO BENEDITO DO SUL","SAO BENTO DO UNA","SAO CAITANO","SAO JOAO",	 "SAO JOAQUIM DO MONTE","SAO JOSE DA COROA GRANDE","SAO JOSE DO BELMONTE","SAO JOSE DO EGITO","SAO LOURENCO DA MATA","SAO VICENTE FERRER","SERRA TALHADA","SERRITA","SERTANIA","SIRINHAEM",	"MOREILANDIA","SOLIDAO","SURUBIM","TABIRA","TACAIMBO","TACARATU","TAMANDARE","TAQUARITINGA DO NORTE","TEREZINHA","TERRA NOVA","TIMBAUBA","TORITAMA","TRACUNHAEM","TRINDADE","TRIUNFO","TUPANATINGA",	"TUPARETAMA","VENTUROSA","VERDEJANTE","VERTENTE DO LORIO","VERTENTES","VICENCIA","VITORIA DE SANTO ANTAO","XEXEU"};
		
		boolean exists = false;
		for (String cidade: cidades_validas) {
			if(cidade == cidade1){
				exists = true;
				break;
			}
		}
		
		return exists;		
	}
}
